_wandb:
    value:
        cli_version: 0.19.7
        code_path: code/src/training/orpo_isaerft_but_sft.py
        m: []
        python_version: 3.11.11
        t:
            "1":
                - 1
                - 5
                - 11
                - 49
                - 51
                - 53
                - 55
                - 71
                - 84
                - 98
                - 105
            "2":
                - 1
                - 5
                - 11
                - 49
                - 51
                - 53
                - 55
                - 71
                - 84
                - 98
                - 105
            "3":
                - 2
                - 15
                - 16
                - 23
                - 55
            "4": 3.11.11
            "5": 0.19.7
            "6": 4.49.0
            "8":
                - 5
            "12": 0.19.7
            "13": linux-x86_64
batch_size:
    value: 4
gradient_accumulation_steps:
    value: 4
learning_rate:
    value: 5e-05
model_name:
    value: EleutherAI/pythia-70m-deduped
num_epochs:
    value: 3
sae_id:
    value: blocks.4.hook_resid_post
sae_release:
    value: pythia-70m-deduped-res-sm
