_wandb:
    value:
        cli_version: 0.19.7
        code_path: code/src/training/orpo_isaerft.py
        m: []
        python_version: 3.11.11
        t:
            "1":
                - 1
                - 5
                - 11
                - 49
                - 51
                - 53
                - 55
                - 71
                - 84
                - 98
                - 105
            "2":
                - 1
                - 5
                - 11
                - 49
                - 51
                - 53
                - 55
                - 71
                - 84
                - 98
                - 105
            "3":
                - 13
                - 15
                - 23
                - 55
            "4": 3.11.11
            "5": 0.19.7
            "6": 4.49.0
            "8":
                - 5
            "12": 0.19.7
            "13": linux-x86_64
